# spell-checker:ignore (libs) mkirf initramfs cpio

[package]
name = "pu_mkirf"
description = "mkirf ~ (peiosutils) compile an initramfs source tree into a deterministic compressed cpio"
repository = "https://github.com/peios/peiosutils/tree/main/src/uu/mkirf"
version.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/mkirf.rs"
doctest = false

[[bin]]
name = "mkirf"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
uucore = { workspace = true }
thiserror = { workspace = true }
flate2 = { workspace = true }
zstd = { workspace = true }
glob = { workspace = true }
notify = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
