[package]
name = "pu_b2sum"
description = "b2sum ~ (peiosutils) Print or check the BLAKE2b checksums"
repository = "https://github.com/peios/peiosutils/tree/main/src/uu/b2sum"
version.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/b2sum.rs"
test = false
doctest = false

[dependencies]
clap = { workspace = true }
uu_checksum_common = { workspace = true }
uucore = { workspace = true, features = [
  "checksum",
  "encoding",
  "sum",
  "hardware",
] }
fluent = { workspace = true }

[dev-dependencies]
uucore = { workspace = true, features = ["benchmark"] }

[[bin]]
name = "b2sum"
path = "src/main.rs"
