# spell-checker:ignore (libs) kqueue
[package]
name = "pu_tail"
description = "tail ~ (peiosutils) display the last lines of input"
repository = "https://github.com/peios/peiosutils/tree/main/src/uu/tail"
version.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/tail.rs"
doctest = false

[dependencies]
clap = { workspace = true }
memchr = { workspace = true }
uucore = { workspace = true, features = [
  "fs",
  "parser-size",
  "signals",
  "pipes",
] }
same-file = { workspace = true }
fluent = { workspace = true }
libc = { workspace = true }
notify = { workspace = true }
rustix = { workspace = true, features = ["fs", "process"] }

[dev-dependencies]
rstest = { workspace = true }

[[bin]]
name = "tail"
path = "src/main.rs"
