[package]
name = "uu_base_common"
description = "Shared encode/decode engine for base32, base64, basenc"
version.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"
test = false
doctest = false

[dependencies]
clap = { workspace = true }
uucore = { workspace = true, features = ["encoding"] }
fluent = { workspace = true }
