[package]
name = "pu_feat"
description = "feat ~ (peiosutils) install/enable Peios features (the imperative layer above packages)"
repository = "https://github.com/peios/peiosutils/tree/main/src/uu/feat"
version.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/feat.rs"
doctest = false

[dependencies]
clap = { workspace = true }
libc = { workspace = true }
uucore = { workspace = true }
peios = { git = "https://github.com/peios/peios-rs.git", rev = "2a2a6bb022192f6e98d4e4a6a7efdbdd40d53b35" }
peios-sys = { git = "https://github.com/peios/peios-rs.git", rev = "2a2a6bb022192f6e98d4e4a6a7efdbdd40d53b35" }

[[bin]]
name = "feat"
path = "src/main.rs"
