[package]
name = "pu_feat"
description = "feat ~ (peiosutils) install/enable Peios features (the imperative layer above packages)"
repository = "https://github.com/peios/peiosutils/tree/main/src/uu/feat"
version.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/feat.rs"
doctest = false

[dependencies]
clap = { workspace = true }
libc = { workspace = true }
serde_json = "1"
toml = "0.8"
uucore = { workspace = true }
peios = { git = "https://github.com/peios/peios-rs.git", rev = "02c87cb643c30eef6b74cd1d9d8b0ae067bed69a" }
peios-sys = { git = "https://github.com/peios/peios-rs.git", rev = "02c87cb643c30eef6b74cd1d9d8b0ae067bed69a" }

[[bin]]
name = "feat"
path = "src/main.rs"
