[package]
name         = "dev.peios.peiosutils-debugsource"
architecture = "noarch"
description  = "Debug sources for peiosutils"



[dependencies]
"dev.peios.peiosutils-debuginfo" = "= {{release}}"

[files]
"@source:LICENSE"       = "usr/share/licenses/dev.peios.peiosutils-debugsource/LICENSE"
":usr/src/debug/**"     = "usr/src/debug"
