[package]
name        = "dev.peios.peiosutils-debuginfo"
description = "Debugging symbols for peiosutils"



[dependencies]
"dev.peios.peiosutils" = "= {{release}}"

[files]
"@source:LICENSE"   = "usr/share/licenses/dev.peios.peiosutils-debuginfo/LICENSE"
":usr/lib/debug/**" = "usr/lib/debug"
