[package]
name         = "dev.peios.peiosutils-debugsource"
architecture = "noarch"
description  = "Debug sources for peiosutils"
license     = "((MIT OR Apache-2.0) AND Unicode-3.0) AND (0BSD OR Apache-2.0 OR MIT) AND Apache-2.0 AND (Apache-2.0 OR BSD-2-Clause OR MIT) AND (Apache-2.0 OR CC0-1.0 OR MIT-0) AND (Apache-2.0 OR GPL-2.0-only) AND (Apache-2.0 OR MIT) AND (Apache-2.0 OR MIT OR Zlib) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND (CC0-1.0 OR Apache-2.0 OR Apache-2.0 WITH LLVM-exception) AND ISC AND MIT AND (MIT OR Unlicense) AND Unicode-3.0 AND Zlib"



[dependencies]
"dev.peios.peiosutils-debuginfo" = "= {{release}}"

[files]
":licenses/**" = "usr/share/licenses/dev.peios.peiosutils-debugsource/third-party"
"@source:LICENSE"       = "usr/share/licenses/dev.peios.peiosutils-debugsource/LICENSE"
":usr/src/debug/**"     = "usr/src/debug"
