[package]
name         = "dev.peios.peiosutils-debugsource"
architecture = "noarch"
description  = "Debug sources for peiosutils"

[provides]
peiosutils-debugsource = "{{version}}-1"

[replaces]
peiosutils-debugsource = "<= 0.1.4-15"

[dependencies]
"dev.peios.peiosutils-debuginfo" = "= {{version}}-1"

[files]
"@source:LICENSE"       = "usr/share/licenses/dev.peios.peiosutils-debugsource/LICENSE"
":usr/src/debug/**"     = "usr/src/debug"
