# spell-checker:ignore (libs) mkuki initramfs cmdline

[package]
name = "pu_mkuki"
description = "mkuki ~ (peiosutils) build a UEFI unified kernel image from Peios boot inputs"
repository = "https://github.com/peios/peiosutils/tree/main/src/uu/mkuki"
version.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/mkuki.rs"
doctest = false

[[bin]]
name = "mkuki"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
uucore = { workspace = true }
notify = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
